package com.bt.passcard.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LogonService", targetNamespace = "http://login.passcard.bt.com/")
public interface LogonService {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "logonCheck", targetNamespace = "http://login.passcard.bt.com/", className = "com.bt.passcard.login.LogonCheck")
	@ResponseWrapper(localName = "logonCheckResponse", targetNamespace = "http://login.passcard.bt.com/", className = "com.bt.passcard.login.LogonCheckResponse")
	public Boolean logonCheck(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

}
